name: TerryLyons.com
favicon: null
layout_spectrum: 0.50423
typography_spectrum: 0.9485894409008324
title: 'Terry Lyons Sports and  Entertainment Marketing & Communications'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080a09'
    - '#c1d4e4'
    - '#818c96'
    - '#373737'
    - '#fefefe'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
